# Generated by Django 4.1.5 on 2023-01-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0003_homepage_opener_image_homepage_opener_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_field', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='opener_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='opener_text',
        ),
    ]
