# Generated by Django 4.1.5 on 2023-04-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_newpage_remove_homepage_opener_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение главной страницы'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заглавный встречающий текст'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительный встречающий текст'),
        ),
    ]
