# Generated by Django 4.1.5 on 2023-04-17 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0005_homepage_main_photo_homepage_main_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slide_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заглавный текст главной страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительный текст главной страницы'),
        ),
    ]
