# Generated by Django 4.1.5 on 2023-04-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_slide_image_alter_homepage_main_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='main_photo',
        ),
    ]
