# Generated by Django 4.1.5 on 2023-04-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_main_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='slide_image',
            new_name='main_image',
        ),
    ]
