# Generated by Django 4.1.5 on 2023-04-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_price_price_price_price_count_price_price_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_me',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='my_skills',
            new_name='skills',
        ),
    ]
