# Generated by Django 4.1.5 on 2023-04-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_products_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='product_title',
            new_name='products_title',
        ),
    ]
