# Generated by Django 4.1.5 on 2023-04-17 23:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0015_rename_product_title_homepage_products_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='adv',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_block', to='home.homepage'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='adv_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='adv_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Введите текст', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='adv_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='advantage_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок блока "Преимущества"'),
        ),
    ]
